# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.0-beta1"
manifest_format = "2.0"
project_hash = "d26d50250af4d93237b73c5a6ecfb0f7ed71dcb9"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
